{% set name = "Exporter" %}
{% set version = "5.74" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/{{ name }}-{{ version }}.tar.gz
    sha256: eadb889ef673ad940da6aa4f6f7d75fc1e625ae786ae3533fd313eaf629945b8
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Copying
    sha256: d77d235e41d54594865151f4751e835c5a82322b0e87ace266567c3391a4b912
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Artistic
    sha256: dd90d4f42e4dcadf5a7c09eea0189d93c7b37ae560c91f0f6d5233ed3b9292a2

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Exporter
    - Exporter::Heavy

about:
  home: https://metacpan.org/release/{{ name }}
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file:
    - Artistic
    - Copying
  summary: Implements default import method for modules

extra:
  recipe-maintainers:
    - tdegeus
